sudo: true

git:
  submodules: false

language: node_js

node_js:
  - "11"

addons:
  apt:
    packages:
      - build-essential
      - libx11-dev
      - libxkbfile-dev
      - execstack
      - libgconf-2-4
      - libsecret-1-dev

matrix:
  include:
    - os: linux
      env: CC=gcc-4.8 CXX=g++-4.8
      dist: trusty

script:
  - npm run lint
  - npm run postinstall
  - DEBUG=electron-packager,electron-osx-sign npm run build

cache:
  directories:
    - node_modules
    - app/node_modules

before_deploy: |
  mkdir -p deploy
  mv app/dist/*.{dmg,zip,deb,rpm} deploy/ || true

deploy:
  - provider: netlify
    local_dir: "deploy/"
    site: "inspiring-volhard-2f86b5"

  - provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file:
      - deploy/**
    skip_cleanup: true
    draft: true
    "on":
      tags: true
